---
title: "Research"
---

My research explores the fascinating field of the neurobiology of language, focusing both on individuals with post-stroke aphasia and those with neurologically intact brains. I am dedicated to studying the neural basis of real-world language processing, leveraging naturalistic stimuli and measures that more closely reflect day-to-day communication abilities. The work that my lab and I conduct follows under two main areas:

### -	Neural correlates of communication deficits in post-stroke aphasia 

This project focuses on ‘functional communication’, that is the ability to reach a communication goal in a real-world context, in individuals with post-stroke aphasia. Our research examines whether we can predict communication outcomes using information from different brain imaging modalities (e.g., lesion size, lesion location, structural and functional connectivity). This research aims to (1) further our understanding of the mechanisms underlying real-world communication and their neural correlates, and (2) create predictive models which can be used to inform clinical prognosis and treatment strategies.

### -	Narrative comprehension

Using functional Magnetic Resonance Imaging (fMRI), this project investigates the roles of the semantic network (particularly the Anterior Temporal Lobe) and Default Mode Network in maintaining a situation model of the narrative (i.e., a mental representation of the events, characters and context in the story).

<br>

## Publications
- Adezati, E., Liu, X., Ding, J., Thye, M., Szaflarski, J. P., & Mirman, D. (2024). Phase synchronization during the processing of taxonomic and thematic relations. Brain and Language, 249, 105379. <https://doi.org/10.1016/j.bandl.2024.105379>

- Adezati, E., Thye, M., Edmondson-Stait, A. J., Szaflarski, J. P., & Mirman, D. (2022). Lesion correlates of auditory sentence comprehension deficits in post-stroke aphasia. Neuroimage: Reports, 2(1), 100076. <https://doi.org/10.1016/j.ynirp.2021.100076>